Import the 🦸🏾‍♀️"Avengers"🦹🏻 data from the [FiveThirtyEight data repository on GitHub](https://github.com/fivethirtyeight/data/blob/master/avengers/avengers.csv).

In [1]:
library('tidyverse')
library('ggrepel')

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
avengers = read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv')
avengers |> head(2)

Rows: 173 Columns: 21

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (18): URL, Name/Alias, Current?, Gender, Probationary Introl, Full/Reser...
dbl  (3): Appearances, Year, Years since joining


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  URL                                                Name/Alias
1 http://marvel.wikia.com/Henry_Pym_(Earth-616)      Henry Jonathan "Hank" Pym
2 http://marvel.wikia.com/Janet_van_Dyne_(Earth-616) Janet van Dyne
  Appearances Current? Gender Probationary Introl Full/Reserve Avengers Intro
1 1269        YES      MALE   NA                  Sep-63
2 1165        YES      FEMALE NA                  Sep-63
  Year Years since joining Honorary ⋯ Return1 Death2 Return2 Death3 Return3
1 1963 52                  Full     ⋯ NO      NA     NA      NA     NA
2 1963 52                  Full     ⋯ YES     NA     NA      NA     NA
  Death4 Return4 Death5 Return5
1 NA     NA      NA     NA
2 NA     NA      NA     NA
  Notes
1 Merged with Ultron in Rage of Ultron Vol. 1. A funeral was held.
2 Dies in Secret Invasion V1:I8. Actually was sent tto Microverse later recovered

Make an ECDF plot 📊 of `Appearances`.

(❗️Hint: combine `arrange`, `mutate` and `row_number`/`rank` to produce a new column to encode with y-position.)

In [3]:
avengers |> 
    select(`Name/Alias`, Appearances) |> 
    arrange(Appearances) |> 
    mutate(rk = row_number() / n()) |> 
    tail(2)

  Name/Alias            Appearances rk
1 Steven Rogers         3458        0.9942197
2 Peter Benjamin Parker 4333        1.0000000

In [4]:
#Using Rank function#
avengers2 = avengers |>
    mutate(ypos = rank(Appearances, ties.method = 'first') / n()) |>
    select(`Name/Alias`, Appearances, ypos) |> 
    arrange(desc(ypos)) |> 
    head(2)

In [5]:
#Using Row_number function#
avengers3 = avengers |>
    select(`Name/Alias`, Appearances) |>
    arrange(Appearances) |>
    mutate(ypos = row_number() / n())

In [6]:
avengers3 |> 
    filter(ypos > 0.80, ypos < 0.85)

  Name/Alias              Appearances ypos
1 Samuel Thomas Wilson    576         0.8034682
2 Alex Summers            592         0.8092486
3 Richard Milhouse Jones  612         0.8150289
4 Daniel Thomas Rand K'ai 629         0.8208092
5 James Buchanan Barnes   663         0.8265896
6 Samuel Guthrie          679         0.8323699
7 Simon Williams          692         0.8381503
8 Heracles                741         0.8439306
9 Flash Thompson          746         0.8497110

In [7]:
p = ggplot(avengers3, aes(x = Appearances, y = ypos)) +
    geom_point() +
    geom_line() +
    geom_text_repel(
        data = highlight, 
        mapping = aes(label = `Name/Alias`),
        hjust = 0,
        nudge_x = 0.5,
        nudge_y = -0.15,
        box.padding = 0.5,
        segment.curvature = 1,
        segment.ncp = 2,
        segment.angle = 0
    ) +
    scale_y_continuous(labels = scales::percent_format())

p

ERROR: Error in fortify(data): object 'highlight' not found